#!/usr/bin/env pwsh
@{
Title='GNU Binutils'
Description=@'
GNU Binutils is a collection of tools for working with binary files. Perhaps the most notable are
ld, a linker, and as, an assembler. Other tools include programs to display binary profiling
information, list the strings in a binary file, and utilities for working with archives. The bfd
library for working with executable and object formats is also included.
'@

Name='binutils'
Version='2.30'

Home=@('https://www.gnu.org/software/binutils/')
BuildDeps=@('glibc')
Upstream='https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.gz'
}
