#!/bin/sh

function provide {
    cd $LFS/sources
    package=$1
    local archive=${package}.tar.xz
    [[ -f $archive ]] || archive=${package}.tar.gz
    [[ -f $archive ]] || archive=${package}.tar.bz2
    rm -rvf $package
    tar xvf $archive
    cd $package
}

echo "5.4. Binutils-2.30 - Pass 1"
# http://ftp.gnu.org/gnu/binutils/binutils-2.30.tar.xz

provide binutils-2.30

mkdir -v build
cd       build

../configure --prefix=/tools       \
        --with-sysroot=$LFS        \
        --with-lib-path=/tools/lib \
        --target=$LFS_TGT          \
        --disable-nls              \
        --disable-werror

#make

#make install
