#!/bin/bash

title="5.6. Linux-4.15.3 API Headers"
name=linux
version=4.15.3
source=(https://www.kernel.org/pub/linux/kernel/v4.x/linux-$version.tar.xz)
deps=()

build() {
    make mrproper
    make INSTALL_HDR_PATH=dest headers_install
}

install() {
    cp -rv dest/include/* /tools/include
}
