#!/bin/bash

title="5.7. Glibc-2.27"
name=glibc
version=2.27
source=(http://ftp.gnu.org/gnu/glibc/glibc-$version.tar.xz)
deps=()
builddir="build"

configure() {
    ../configure                            \
        --prefix=/tools                     \
        --host=$LFS_TGT                     \
        --build=$(../scripts/config.guess)  \
        --enable-kernel=3.2                 \
        --with-headers=/tools/include       \
        libc_cv_forced_unwind=yes           \
        libc_cv_c_cleanup=yes
}

build() {
    make
}

install() {
    make install
}
