#!/bin/bash

title="5.8. Libstdc++-7.3.0"
name=gcc
version=7.3.0
source=(http://ftp.gnu.org/gnu/gcc/gcc-7.3.0/gcc-7.3.0.tar.xz)
builddir=build

configure() {
    ../libstdc++-v3/configure           \
        --host=$LFS_TGT                 \
        --prefix=/tools                 \
        --disable-multilib              \
        --disable-nls                   \
        --disable-libstdcxx-threads     \
        --disable-libstdcxx-pch         \
        --with-gxx-include-dir=/tools/$LFS_TGT/include/c++/7.3.0
}

build() {
    make
}

install() {
    make install
}
