#!/bin/bash

title="5.9. Binutils-2.30 - Pass 2"
name=binutils
version=2.30
source=(http://ftp.gnu.org/gnu/binutils/binutils-$version.tar.xz)
builddir=build

configure() {
    CC=$LFS_TGT-gcc                 \
    AR=$LFS_TGT-ar                  \
    RANLIB=$LFS_TGT-ranlib          \
    ../configure                    \
        --prefix=/tools             \
        --disable-nls               \
        --disable-werror            \
        --with-lib-path=/tools/lib  \
        --with-sysroot
}

build() {
    make
}

install() {
    make install
    make -C ld clean
    make -C ld LIB_PATH=/usr/lib:/lib
    cp -v ld/ld-new /tools/bin
}
