#!/bin/bash

title="5.11. Tcl-core-8.6.8"
name=tcl
version=8.6.8
source=(https://downloads.sourceforge.net/tcl/tcl$version-src.tar.gz)
builddir=unix

configure() {
    ./configure --prefix=/tools
}

build() {
    make
}

install() {
    make install

    chmod -v u+w /tools/lib/libtcl8.6.so

    make install-private-headers

    ln -sv tclsh8.6 /tools/bin/tclsh
}
