#!/bin/bash

title="5.12. Expect-5.45.4"
name=expect
version=5.45.4
source=(http://prdownloads.sourceforge.net/expect/expect${version}.tar.gz)

configure() {
    cp -v configure{,.orig}
    sed 's:/usr/local/bin:/bin:' configure.orig > configure

    ./configure --prefix=/tools     \
        --with-tcl=/tools/lib       \
        --with-tclinclude=/tools/include
}

build() {
    make
}

install() {
    make SCRIPTS="" install
}
