#!/bin/bash

title="5.13. DejaGNU-1.6.1"
name=dejagnu
version=1.6.1
source=(http://ftp.gnu.org/gnu/dejagnu/dejagnu-$version.tar.gz)

configure() {
    ./configure --prefix=/tools
}

install() {
    make install
    make check
}
