#!/bin/bash

title="5.14. M4-1.4.18"
name=m4
version=1.4.18
source=(http://ftp.gnu.org/gnu/m4/m4-$version.tar.xz)

configure() {
    ./configure --prefix=/tools
}

build() {
    make
}

install() {
    make install
}
