#!/bin/bash

title="5.15. Ncurses-6.1"
name=ncurses
version=6.1
source=(http://ftp.gnu.org/gnu/ncurses/ncurses-$version.tar.gz)

configure() {
    sed -i s/mawk// configure

    ./configure --prefix=/tools \
                --with-shared   \
                --without-debug \
                --without-ada   \
                --enable-widec  \
                --enable-overwrite
}

build() {
    make
}

install() {
    make install
}
