#!/bin/bash

title="5.16. Bash-4.4.18"
name=bash
version=4.4.18
source=(http://ftp.gnu.org/gnu/bash/bash-$version.tar.gz)

configure() {
    ./configure --prefix=/tools --without-bash-malloc
}

build() {
    make
}

install() {
    make install
    ln -sv bash /tools/bin/sh
}
