#!/bin/bash

title="5.17. Bison-3.0.4"
name=bison
version=3.0.4
source=(http://ftp.gnu.org/gnu/bison/bison-$version.tar.xz)

configure() {
    ./configure --prefix=/tools
}

build() {
    make
}

install() {
    make install
}
