#!/bin/bash

title="5.21. File-5.32"
name=file
version=5.32
source=(ftp://ftp.astron.com/pub/file/file-$version.tar.gz)

configure() {
    ./configure --prefix=/tools
}

build() {
    make
}

install() {
    make install
}
