#!/bin/bash

title="5.23. Gawk-4.2.0"
name=gawk
version=4.2.0
source=(http://ftp.gnu.org/gnu/gawk/gawk-$version.tar.xz)

configure() {
    ./configure --prefix=/tools
}

build() {
    make
}

install() {
    make install
}
