#!/bin/bash

title="5.24. Gettext-0.19.8.1"
name=gettext
version=0.19.8.1
source=(http://ftp.gnu.org/gnu/gettext/gettext-$version.tar.xz)
builddir=gettext-tools

configure() {
    EMACS="no" ./configure --prefix=/tools --disable-shared
}

build() {
    make -C gnulib-lib
    make -C intl pluralx.c
    make -C src msgfmt
    make -C src msgmerge
    make -C src xgettext
}

install() {
    cp -v src/{msgfmt,msgmerge,xgettext} /tools/bin
}
