#!/bin/bash

title="5.25. Grep-3.1"
name=grep
version=3.1
source=(http://ftp.gnu.org/gnu/grep/grep-$version.tar.xz)

configure() {
    ./configure --prefix=/tools
}

build() {
    make
}

install() {
    make install
}
