#!/bin/bash

title="5.29. Perl-5.26.1"
name=perl
version=5.26.1
source=(http://www.cpan.org/src/${version:0:1}.0/perl-$version.tar.xz)

configure() {
    sh Configure -des -Dprefix=/tools -Dlibs=-lm
}

build() {
    make
}

install() {
    cp -v perl cpan/podlators/scripts/pod2man /tools/bin
    mkdir -pv /tools/lib/perl5/5.26.1
    cp -Rv lib/* /tools/lib/perl5/5.26.1
}
