#!/bin/bash

title="5.32. Texinfo-6.5"
name=texinfo
version=6.5
source=(http://ftp.gnu.org/gnu/texinfo/texinfo-$version.tar.xz)

configure() {
    ./configure --prefix=/tools
}

build() {
    make
}

install() {
    make install
}
