#!/bin/bash

title="5.33. Util-linux-2.31.1"
name=util-linux
version=2.31.1
source=(https://www.kernel.org/pub/linux/utils/util-linux/v${version:0:4}/util-linux-$version.tar.xz)

configure() {
    ./configure --prefix=/tools                 \
                --without-python                \
                --disable-makeinstall-chown     \
                --without-systemdsystemunitdir  \
                --without-ncurses               \
                PKG_CONFIG=""
}

build() {
    make
}

install() {
    make install
}
