#!/bin/bash

title="5.34. Xz-5.2.3"
name=xz
version=5.2.3
source=(http://tukaani.org/xz/xz-$version.tar.xz)

configure() {
    ./configure --prefix=/tools
}

build() {
    make
}

install() {
    make install
}
