#!/usr/bin/env bash

# expect environment variables:
#   McName      - name of package
#   McVersion   - version of package

case "${1,,}" in
    -configure) 
        ;;
    -make)
        ;;
    -install)
        ;;
    *) exit 127
esac