#!/bin/bash (source only)

Title="Linux Headers"
Name=LinuxHeaders
Version=4.15.3
Supplies=(https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.15.3.tar.xz)

Build()
{
    make mrproper
    make INSTALL_HDR_PATH=dest headers_install
    find dest/include \( -name .install -o -name ..install.cmd \) -delete
    cp -rv dest/include/* /usr/include
}
