#!/bin/bash

Title="6.17. GMP-6.1.2"
Name=gmp
Version=6.1.2
Supplies=(http://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.xz)

Build ()
{
    ./configure \
        --prefix=/usr       \
        --enable-cxx        \
        --disable-static    \
        --docdir=/usr/share/doc/gmp

    make
    make html

    make install
    make install-html
}
