#!/bin/bash

Title="6.18. MPFR-4.0.1"
Name=Mpfr
Version=4.0.1
Supplies=(http://www.mpfr.org/mpfr-4.0.1/mpfr-4.0.1.tar.xz)

Build ()
{
    ./configure \
        --prefix=/usr           \
        --disable-static        \
        --enable-thread-safe    \
        --docdir=/usr/share/doc/mpfr-4.0.1

    make
    make html

    make check

    make install
    make install-html
}
