#!/bin/bash

Title="6.19. MPC-1.1.0"
Name=Mpc
Version=1.1.0
Supplies=(https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz)

Build ()
{
    ./configure \
        --prefix=/usr    \
        --disable-static \
        --docdir=/usr/share/doc/mpc-1.1.0

    make
    make html

    #make check

    make install
    make install-html
}
