#!/bin/bash

Title="6.21. Bzip2-1.0.6"
Name=bzip2
Version=1.0.6
Supplies=(
    http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
    http://www.linuxfromscratch.org/patches/lfs/8.2/bzip2-1.0.6-install_docs-1.patch
)

Build ()
{
    patch -Np1 -i ../bzip2-1.0.6-install_docs-1.patch

    sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile

    sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile

    make -f Makefile-libbz2_so
    make clean

    make

    make PREFIX=/usr install

    cp -v bzip2-shared /bin/bzip2
    cp -av libbz2.so* /lib
    ln -vfs ../../lib/libbz2.so.1.0 /usr/lib/libbz2.so
    rm -vf /usr/bin/{bunzip2,bzcat,bzip2}
    ln -vsf bzip2 /bin/bunzip2
    ln -vsf bzip2 /bin/bzcat
}
