#!/bin/bash

Title="6.22. Pkg-config-0.29.2"
Name=pkg-config
Version=0.29.2
Supplies=(https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz)

Build ()
{
    ./configure \
        --prefix=/usr              \
        --with-internal-glib       \
        --disable-host-tool        \
        --docdir=/usr/share/doc/pkg-config-0.29.2
    
    make
    #make check
    make install
}
