#!/bin/bash

Title="6.23. Ncurses-6.1"
Name=NCurses
Version=6.1
Supplies=(http://ftp.gnu.org/gnu//ncurses/ncurses-6.1.tar.gz)

Build ()
{
    sed -i '/LIBTOOL_INSTALL/d' c++/Makefile.in

    ./configure --prefix=/usr           \
                --mandir=/usr/share/man \
                --with-shared           \
                --without-debug         \
                --without-normal        \
                --enable-pc-files       \
                --enable-widec

    make

    make install

    mv -vf /usr/lib/libncursesw.so.6* /lib

    ln -vsf ../../lib/$(readlink /usr/lib/libncursesw.so) /usr/lib/libncursesw.so

    for lib in ncurses form panel menu ; do
        rm -vf                    /usr/lib/lib${lib}.so
        echo "INPUT(-l${lib}w)" > /usr/lib/lib${lib}.so
        ln -sfv ${lib}w.pc        /usr/lib/pkgconfig/${lib}.pc
    done

    rm -vf                     /usr/lib/libcursesw.so
    echo "INPUT(-lncursesw)" > /usr/lib/libcursesw.so
    ln -sfv libncurses.so      /usr/lib/libcurses.so

    mkdir -v       /usr/share/doc/ncurses-6.1
    cp -v -R doc/* /usr/share/doc/ncurses-6.1
}
