#!/bin/bash

Title="6.24. Attr-2.4.47"
Name=attr
Version=2.4.47
Supplies=(http://download.savannah.gnu.org/releases/attr/attr-2.4.47.src.tar.gz)

Build ()
{
    sed -i -e 's|/@pkg_name@|&-@pkg_version@|' include/builddefs.in

    sed -i -e "/SUBDIRS/s|man[25]||g" man/Makefile

    sed -i 's:{(:\\{(:' test/run

    ./configure \
        --prefix=/usr \
        --disable-nls \
        --bindir=/bin \
        --disable-static

    make

    #make -j1 tests root-tests

    make install install-dev install-lib
    chmod -v 755 /usr/lib/libattr.so

    mv -v /usr/lib/libattr.so.* /lib
    ln -sfv ../../lib/$(readlink /usr/lib/libattr.so) /usr/lib/libattr.so
}
