#!/bin/bash

Title="6.26. Libcap-2.25"
Name=Libcap
Version=2.25
Supplies=(https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.25.tar.xz)

Build ()
{
    sed -i '/install.*STALIBNAME/d' libcap/Makefile

    make

    make RAISE_SETFCAP=no lib=lib prefix=/usr install
    chmod -v 755 /usr/lib/libcap.so

    mv -v /usr/lib/libcap.so.* /lib
    ln -sfv ../../lib/$(readlink /usr/lib/libcap.so) /usr/lib/libcap.so
}
