#!/bin/bash

Title="6.27. Sed-4.4"
Name=Sed
Version=4.4
Supplies=(http://ftp.gnu.org/gnu/sed/sed-4.4.tar.xz)

Build ()
{
    sed -i 's/usr/tools/'                 build-aux/help2man
    sed -i 's/testsuite.panic-tests.sh//' Makefile.in

    ./configure --prefix=/usr --bindir=/bin

    make
    make html

    make check

    make install
    install -d -m755           /usr/share/doc/sed-4.4
    install -m644 doc/sed.html /usr/share/doc/sed-4.4
}
