#!/bin/bash

Title="6.28. Shadow-4.5"
Name=Shadow
Version=4.5
Supplies=(https://github.com/shadow-maint/shadow/releases/download/4.5/shadow-4.5.tar.xz)

Build ()
{
    # DISABLED
    touch /tmp/shadow
}
