#!/bin/bash

Title="6.31. Bison-3.0.4"
Name=Bison
Version=3.0.4
Supplies=(http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.xz)

Build ()
{
    ./configure --prefix=/usr \
                --disable-nls \
                --docdir=/usr/share/doc/bison-3.0.4

    make

    make install
}
