#!/bin/bash

Title="6.35. Libtool-2.4.6"
Name=libtools
Version=2.4.6
Supplies=(http://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.xz)

Build ()
{    
    ./configure --prefix=/usr
    
    make
    #make check
    make install
}
