#!/bin/bash

Title="6.38. Expat-2.2.5"
Name=Expat
Version=2.2.5
Supplies=(http://prdownloads.sourceforge.net/expat/expat-2.2.5.tar.bz2)

Build ()
{
    sed -i 's|usr/bin/env |bin/|' run.sh.in

    ./configure --prefix=/usr \
                --disable-static

    make
    #make check
    make install

    install -v -dm755 /usr/share/doc/expat-2.2.5
    install -v -m644 doc/*.{html,png,css} /usr/share/doc/expat-2.2.5
}
