#!/bin/bash

Title="6.46. Kmod-25"
Name=kmod
Version=25
Supplies=(https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-25.tar.xz)

Build ()
{
    # DISABLED
    return 0

    ./configure --prefix=/usr          \
                --bindir=/bin          \
                --sysconfdir=/etc      \
                --with-rootlibdir=/lib \
                --with-xz              \
                --with-zlib
            
    make
    
    make install

    for target in depmod insmod lsmod modinfo modprobe rmmod; do
    ln -sfv ../bin/kmod /sbin/$target
    done

    ln -sfv kmod /bin/lsmod
}
