#!/bin/bash

Title="6.47. Gettext-0.19.8.1"
Name=gettext
Version=0.19.8.1
Supplies=(http://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.xz)

Build ()
{
    # First, suppress two invocations of test-lock which on some machines can loop forever: 
    sed -i '/^TESTS =/d' gettext-runtime/tests/Makefile.in &&
    sed -i 's/test-lock..EXEEXT.//' gettext-tools/gnulib-tests/Makefile.in

    # Prepare Gettext for compilation: 
    ./configure --prefix=/usr       \
                --disable-nls       \
                --disable-static    \
                --docdir=/usr/share/doc/gettext-0.19.8.1

    # Compile the package: 
    make

    # To test the results (this takes a long time, around 3 SBUs), issue: 
    #make check

    # Install the package: 
    make install
    chmod -v 0755 /usr/lib/preloadable_libintl.so
}
