#!/bin/bash

Title="6.50. OpenSSL-1.1.0g"
Name=openssl
Version=1.1.0g
Supplies=(https://openssl.org/source/openssl-1.1.0g.tar.gz)

Build ()
{
    # Prepare OpenSSL for compilation: 
    ./config --prefix=/usr          \
            --openssldir=/etc/ssl   \
            --libdir=lib            \
            shared                  \
            zlib-dynamic

    # Compile the package: 
    make

    # To test the results, issue: 
    # One subtest in the test 40-test_rehash.t fails in the lfs chroot environment, but passes when run as a regular user. 
    #make test

    # Install the package: 
    sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile
    make MANSUFFIX=ssl install

    # If desired, install the documentation: 
    mv -v /usr/share/doc/openssl /usr/share/doc/openssl-1.1.0g
    cp -vfr doc/* /usr/share/doc/openssl-1.1.0g
}
