#!/bin/bash

Title="6.52. Ninja-1.8.2"
Name=Ninja
Version=1.8.2
Supplies=(https://github.com/ninja-build/ninja/archive/v1.8.2/ninja-1.8.2.tar.gz)

Build ()
{
    # Build Ninja with: 
    python3 configure.py --bootstrap
    # The meaning of the build option: 
    #   --bootstrap 
    # This parameter forces ninja to rebuild itself for the current system. 

    # To test the results, issue: 
    #python3 configure.py
    #./ninja ninja_test
    #./ninja_test --gtest_filter=-SubprocessTest.SetWithLots

    # Install the package: 
    install -vm755 ninja /usr/bin/
    install -vDm644 misc/bash-completion /usr/share/bash-completion/completions/ninja
    install -vDm644 misc/zsh-completion  /usr/share/zsh/site-functions/_ninja
}
