#!/bin/bash

Title="6.57. Check-0.12.0"
Name=check
Version=0.12.0
Supplies=(https://github.com/libcheck/check/releases/download/0.12.0/check-0.12.0.tar.gz)

Build ()
{
    # Prepare Check for compilation: 
    ./configure --prefix=/usr

    # Build the package: 
    make

    # Compilation is now complete. To run the Check test suite, issue the following command: 
    # Note that the Check test suite may take a relatively long (up to 4 SBU) time. 
    #make check

    # Install the package: 
    make install
}
