#!/bin/bash

Title="6.59. Gawk-4.2.0"
Name=Gawk
Version=4.2.0
Supplies=(http://ftp.gnu.org/gnu/gawk/gawk-4.2.0.tar.xz)

Build ()
{
    # First, ensure some unneeded files are not installed: 
    sed -i 's/extras//' Makefile.in

    # Prepare Gawk for compilation: 
    ./configure \
        --prefix=/usr \
        --disable-nls

    # Compile the package: 
    make

    # To test the results, issue: 
    #make check

    # Install the package: 
    make install
    
    # If desired, install the documentation: 
    mkdir -v /usr/share/doc/gawk-4.2.0
    cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk-4.2.0
}
