#!/bin/bash

Title="6.60. Findutils-4.6.0"
Name=findutils
Version=4.6.0
Supplies=(http://ftp.gnu.org/gnu/findutils/findutils-4.6.0.tar.gz)

Build ()
{
    # First, suppress a test which on some machines can loop forever: 
    sed -i 's/test-lock..EXEEXT.//' tests/Makefile.in

    # Prepare Findutils for compilation: 
    ./configure \
        --prefix=/usr \
        --disable-nls \
        --localstatedir=/var/lib/locate
    # The meaning of the configure options: 
    # --localstatedir 
    # This option changes the location of the locate database to be in /var/lib/locate, which is FHS-compliant. 

    # Compile the package: 
    make

    # To test the results, issue: 
    #make check

    # Install the package: 
    make install

    # Some of the scripts in the LFS-Bootscripts package depend on find.
    # As /usr may not be available during the early stages of booting,
    # this program needs to be on the root partition.
    # The updatedb script also needs to be modified to correct an explicit path: 
    mv -v /usr/bin/find /bin
    sed -i 's|find:=${BINDIR}|find:=/bin|' /usr/bin/updatedb
}
