#!/bin/bash

Title="6.65. IPRoute2-4.15.0"
Name=iproute2
Version=4.15.0
Supplies=(https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-4.15.0.tar.xz)

Build ()
{
    sed -i /ARPD/d Makefile
    rm -fv man/man8/arpd.8
    sed -i 's/m_ipt.o//' tc/Makefile
    make
    make DOCDIR=/usr/share/doc/iproute2-4.15.0 install
}
