#!/bin/bash

Title="6.66. Kbd-2.0.4"
Name=Kbd
Version=2.0.4
Supplies=(
    https://www.kernel.org/pub/linux/utils/kbd/kbd-2.0.4.tar.xz
    http://www.linuxfromscratch.org/patches/lfs/8.2/kbd-2.0.4-backspace-1.patch
)

Build ()
{
    patch -Np1 -i ../kbd-2.0.4-backspace-1.patch

    sed -i 's/\(RESIZECONS_PROGS=\)yes/\1no/g' configure
    sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

    PKG_CONFIG_PATH=/tools/lib/pkgconfig \
    ./configure \
        --prefix=/usr   \
        --disable-nls   \
        --disable-vlock

    make
    # make check
    make install

    mkdir -v       /usr/share/doc/kbd-2.0.4
    cp -R -v docs/doc/* /usr/share/doc/kbd-2.0.4
}
