#!/bin/bash

Title="6.74. Man-DB-2.8.1"
Name=man-db
Version=2.8.1
Supplies=(http://download.savannah.gnu.org/releases/man-db/man-db-2.8.1.tar.xz)

Build ()
{
    ./configure \
        --prefix=/usr                   \
        --disable-nls                   \
        --docdir=/usr/share/doc/man-db  \
        --sysconfdir=/etc               \
        --disable-setuid                \
        --enable-cache-owner=bin        \
        --with-browser=/usr/bin/lynx    \
        --with-vgrind=/usr/bin/vgrind   \
        --with-grap=/usr/bin/grap       \
        --with-systemdtmpfilesdir=

    make
    make install
}
