#!/bin/bash (source only)

Title="6.7. Linux-4.15.3 API Headers"
Home=(https://www.kernel.org/)
Name=linux-headers
Version=4.15.3
Supplies=(https://www.kernel.org/pub/linux/kernel/v${Version:0:1}.x/linux-$Version.tar.xz)

Build()
{
    make mrproper
    make INSTALL_HDR_PATH=dest headers_install
    find dest/include \( -name .install -o -name ..install.cmd \) -delete
    cp -rv dest/include/* /usr/include
}
