#!/bin/bash

Title="Attr"
Home=(https://savannah.nongnu.org/projects/attr/)
Name=attr
Version=2.4.47
Supplies=(http://download.savannah.nongnu.org/releases/attr/attr-$Version.src.tar.gz)

Build ()
{
    sed -i -e "/SUBDIRS/s|man[25]||g" man/Makefile

    sed -i 's:{(:\\{(:' test/run

    ./configure \
        --prefix=/usr           \
        --disable-static        \
        --libexecdir=/usr/lib
     
    make
    make install install-dev install-lib
    chmod -v 755 /usr/lib/libattr.so
}

Cleanup ()
{
    RemoveDir usr/share/locale
}
