#!/bin/bash

Title="AutoConf"
Home=(https://www.gnu.org/software/autoconf/)
Name=autoconf
Version=2.69
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.xz)

Build()
{
    ./configure --prefix=/usr
    make
    make install
}
