#!/bin/bash

Title="The GNU Bourne-Again SHell"
Home=(https://www.gnu.org/software/bash/ https://tiswww.case.edu/php/chet/bash/bashtop.html)
Name=bash
Version=4.4.18
BuildDeps=(readline libiconv gettext ncurses)
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.gz)

Build()
{
    ./configure \
        --prefix=/usr               \
        --disable-nls               \
        --without-bash-malloc       \
        --with-installed-readline
    
    make
    make install
    #ln -vfsr /usr/bin/bash /bin/bash
    ln -vfs bash /usr/bin/sh
}
