#!/bin/bash

Title="GNU bc"
Home=(https://www.gnu.org/software/bc/)
Name=bc
Version=1.07.1
ToolDeps=(flex ed)
BuildDeps=(readline)
Supplies=(https://ftpmirror.gnu.org/gnu/bc/bc-$Version.tar.gz)

Build()
{
    ./configure \
        --prefix=/usr           \
        --disable-nls           \
        --with-readline         \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info

    make
    #echo "quit" | ./bc/bc -l Test/checklib.b
    make install
}
