#!/bin/bash

Title="Bison"
Home=(https://www.gnu.org/software/bison/)
Name=bison
Version=3.0.4
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.xz)

Build()
{
    ./configure --prefix=/usr \
                --disable-nls \
                --disable-static

    make
    make install
}
