#!/bin/bash

Title="BZip2"
Home=(http://www.bzip.org/)
Name=BZip2
Version=1.0.6
Supplies=(http://www.bzip.org/$Version/bzip2-$Version.tar.gz)

Build()
{
    # make relative symlinks
    sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile

    # man pages to /usr/share/man
    sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile

    make -f Makefile-libbz2_so
    make clean
    make
    make PREFIX=/usr install

    install -v -d -m755 /usr/share/doc/bzip2
    install -v -m644 manual.ps manual.html manual.pdf bzip2.txt /usr/share/doc/bzip2

    cp -vf bzip2-shared /usr/bin/bzip2
    cp -av libbz2.so* /usr/lib
    rm -vf /usr/bin/{bunzip2,bzcat}
    ln -vsf bzip2 /bin/bunzip2
    ln -vsf bzip2 /bin/bzcat
}
