#!/bin/bash

Title="CMake"
Home="https://cmake.org/"
Name=cmake
Version=3.11.2
BuildDeps=(libuv expat)
Supplies=(https://cmake.org/files/v3.11/cmake-$Version.tar.gz)

Build()
{
    sed -i '/"lib64"/s/64//' Modules/GNUInstallDirs.cmake

    ./bootstrap \
        --prefix=/usr        \
        --system-libs        \
        --mandir=/share/man  \
        --no-system-jsoncpp  \
        --no-system-librhash

    make
    make install
}
