#!/bin/bash

Title="DoxyGen"
Home="http://www.doxygen.org/"
Name=DoxyGen
Version=1.8.14
BuildIn=build
BuildDeps=(CMake)
RunDeps()
Supplies=(http://ftp.stack.nl/pub/doxygen/doxygen-1.8.14.src.tar.gz )

Build()
{
    cmake -G "Unix Makefiles"         \
        -DCMAKE_BUILD_TYPE=Release  \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -Wno-dev ..

    make

    cmake -DDOC_INSTALL_DIR=share/doc/doxygen-1.8.14 -Dbuild_doc=ON ..

    make docs

    make install
    install -vm644 ../doc/*.1 /usr/share/man/man1
}
