#!/bin/bash

Title="DoxyGen"
Home="http://www.doxygen.org/"
Name=doxygen
Version=1.8.14
BuildIn=build
ToolDeps=(cmake)
Supplies=(http://ftp.stack.nl/pub/doxygen/doxygen-$Version.src.tar.gz )

Build()
{
    cmake -G "Unix Makefiles"         \
        -DCMAKE_BUILD_TYPE=Release  \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -Wno-dev ..

    make

    make install
    install -vm644 ../doc/*.1 /usr/share/man/man1
}
