#!/bin/bash (source-only)

Title="GNU ed"
Home=(https://www.gnu.org/software/ed/)
Name=ed
Version=1.14.2
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.lz)

Build()
{
    ./configure \
        --prefix=/usr \
        --bindir=/bin

    make
    make install
}
