#!/bin/bash

Title="Expat XML parser"
Home=(https://libexpat.github.io/)
Name=expat
Version=2.2.5
Supplies=(https://github.com/libexpat/libexpat/releases/download/R_2_2_5/expat-2.2.5.tar.bz2)

Build()
{
    sed -i 's|usr/bin/env |bin/|' run.sh.in

    ./configure \
        --prefix=/usr \
        --disable-static

    make
    make install

    install -v -dm755 /usr/share/doc/expat
    install -v -m644 doc/*.{html,png,css} /usr/share/doc/expat
}
