#!/bin/bash

Title="File"
Home=(http://www.darwinsys.com/file/ http://directory.fsf.org/file.html)
Name=file
Version=5.33
Supplies=(ftp://ftp.astron.com/pub/file/file-$Version.tar.gz)

Build()
{
    ./configure \
        --prefix=/usr \
        --disable-nls

    make
    make install
}
