#!/bin/bash

Title="Flex"
Home=(https://github.com/westes/flex)
Name=Flex
Version=2.6.4
Supplies=(https://github.com/westes/flex/releases/download/v$Version/flex-$Version.tar.gz)

Build()
{
    sed -i "/math.h/a #include <malloc.h>" src/flexdef.h

    ./configure \
        --prefix=/usr   \
        --disable-nls   \
        --disable-static

    make
    make install
    ln -vfs flex /usr/bin/lex
}
