#!/bin/bash

Title="GNU Awk"
Home=(https://www.gnu.org/software/gawk/)
Name=gawk
Version=4.2.1
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.xz)

Build()
{
    ./configure \
        --prefix=/usr           \
        --disable-nls           \
        --sysconfdir=/etc

    make
    make install
    
    mkdir -pv /usr/share/doc/gawk
    cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk
}

Cleanup ()
{
    RemoveFile ./usr/bin/$Name-$Version
    RemoveDir ./usr/libexec     # grcat pwcat
    Rename ./usr/share/awk ./usr/share/gawk
}
