#!/bin/bash

Title="GCC"
Home=(https://www.gnu.org/software/gcc/)
Name=gcc
Version=7.3.0
BuildIn=build
BuildDeps=(isl gmp mpfr mpc zlib)
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version/$Name-$Version.tar.xz)

Build()
{
    sed -e '/m64=/s/lib64/lib/' -i.orig ../gcc/config/i386/t-linux64

    SED=sed                         \
    ../configure                    \
        --prefix=/usr               \
        --libexecdir=/usr/lib       \
        --disable-nls               \
        --disable-bootstrap         \
        --disable-multilib          \
        --with-system-zlib          \
        --enable-languages=c,c++

    make

    make install

    mkdir -pv /usr/share/gdb/auto-load/usr/lib
    mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib

    ln -vsf ../usr/bin/cpp /lib
    ln -vsf gcc /usr/bin/cc
    install -v -dm755 /usr/lib/bfd-plugins
    ln -vsf ../../lib/gcc/$(gcc -dumpmachine)/7.3.0/liblto_plugin.so /usr/lib/bfd-plugins/
}
