#!/bin/bash

Title="GNU dbm"
Home=(https://www.gnu.org/software/gdbm/)
Name=gdbm
Version=1.14.1
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.gz)

Build()
{
    ./configure \
        --prefix=/usr       \
        --disable-nls       \
        --disable-static    \
        --enable-libgdbm-compat    

    make
    make install
}
