#!/bin/bash

Title="GNU gettext"
Home=(https://www.gnu.org/software/gettext/)
Name=gettext
Version=0.19.8.1
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.xz)

Build()
{
    ./configure \
        --prefix=/usr       \
        --disable-nls       \
        --disable-static

    make
    make install
    chmod -v 0755 /usr/lib/preloadable_libintl.so
}
