#!/bin/bash

Title="The GNU C Library (glibc)"
Home="https://www.gnu.org/software/libc/"
Name=glibcx
Version=2.27
BuildIn=build
BuildDeps=(linux-headers)
Supplies=(
    https://ftpmirror.gnu.org/gnu/glibc/glibc-$Version.tar.xz
    http://www.linuxfromscratch.org/patches/lfs/8.2/glibc-2.27-fhs-1.patch
)

Prepare ()
{
    patch -Np1 -i ../glibc-2.27-fhs-1.patch
}

Build() 
{
    #ln -sfv /tools/lib/gcc /usr/lib

    #GCC_INCDIR=/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include
    #ln -sfv ../lib/ld-linux-x86-64.so.2 /lib64
    #ln -sfv ../lib/ld-linux-x86-64.so.2 /lib64/ld-lsb-x86-64.so.3

    rm -f /usr/include/limits.h

    #CC="gcc -isystem $GCC_INCDIR -isystem /usr/include" \
    ../configure \
        --prefix=/usr                   \
        --disable-werror                \
        --enable-kernel=3.2             \
        --enable-stack-protector=strong \
        libc_cv_slibdir=/lib
    unset GCC_INCDIR

    make

    #make check

    touch /etc/ld.so.conf

    sed '/test-installation/s@$(PERL)@echo not running@' -i ../Makefile

    make install

    cp -v ../nscd/nscd.conf /etc/nscd.conf
    mkdir -pv /var/cache/nscd
}    
