#!/bin/bash

Title="The GNU C Library (glibc)"
Home="https://www.gnu.org/software/libc/"
Name=glibc
Version=2.27
BuildIn=build
BuildDeps=(linux-headers)
Supplies=()

Build() 
{
    /Data/Variable/Store/Tools/GLibc-2.27/Files.tar.xz
}    
