#!/bin/bash

Title="The GNU Multiple Precision Arithmetic Library"
Home="https://gmplib.org/"
Name=gmp
Version=6.1.2
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.xz)

Build()
{
    ./configure \
        --prefix=/usr       \
        --enable-cxx        \
        --disable-static    \
        --docdir=/usr/share/doc/gmp

    make
    make html

    make install
    make install-html
}
