#!/bin/bash

Title="GPerf"
Home=(https://www.gnu.org/software/gperf/ http://savannah.gnu.org/projects/gperf/)
Name=gperf
Version=3.1
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.gz)

Build()
{
    ./configure --prefix=/usr --disable-nls

    make
    make install
}
