#!/bin/bash

Title="Grep"
Home=(https://www.gnu.org/software/grep/)
Name=Grep
Version=3.1
Supplies=(https://ftpmirror.gnu.org/gnu/grep/grep-$Version.tar.xz)

Build()
{
    ./configure --prefix=/usr   \
                --disable-nls

    make
    make install
}
