#!/bin/bash

Title="GNU Gzip"
Home=(https://www.gnu.org/software/gzip/)
Name=gzip
Version=1.9
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.xz)

Build()
{
    ./configure --prefix=/usr
    make
    make install
}
