#!/bin/bash

Title="IanaEtc"
Home=(https://www.iana.org/protocols/)
Name=IanaEtc
Version=2.30
Supplies=(http://anduin.linuxfromscratch.org/LFS/iana-etc-2.30.tar.bz2)

Build ()
{
    make
    make install
}
