#!/bin/bash

Title="Inetutils - GNU network utilities"
Home=(https://www.gnu.org/software/inetutils/)
Name=inetutils
Version=1.9.4
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.xz)

Build()
{
    ./configure --prefix=/usr        \
                --localstatedir=/var \
                --disable-logger     \
                --disable-whois      \
                --disable-rcp        \
                --disable-rexec      \
                --disable-rlogin     \
                --disable-rsh        \
                --disable-servers

    make
    make install
}
