#!/bin/bash

Title="6.42. Intltool-0.51.0"
Home=(https://www.gnu.org/software/inetutils/)
Name=IntlTool
Version=0.51.0
BuildDeps=(Perl)
Supplies=(http://launchpad.net/intltool/trunk/$Version/+download/intltool-$Version.tar.gz)

Build ()
{
    # First fix a warning that is caused by perl-5.22 and later:
    sed -i 's:\\\${:\\\$\\{:' intltool-update.in

    ./configure --prefix=/usr

    make
    make install
    install -v -Dm644 doc/I18N-HOWTO /usr/share/doc/intltool-0.51.0/I18N-HOWTO
}
