#!/bin/bash

Title="6.42. Intltool-0.51.0"
Home=(https://launchpad.net/intltool)
Name=intltool
Version=0.51.0
BuildDeps=(perl)
Supplies=(http://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz)

Build ()
{
    # First fix a warning that is caused by perl-5.22 and later:
    sed -i 's:\\\${:\\\$\\{:' intltool-update.in

    ./configure --prefix=/usr

    make
    make install
    install -v -Dm644 doc/I18N-HOWTO /usr/share/doc/intltool/I18N-HOWTO
}
