#!/bin/bash

Title="Integer Set Library"
Home=(http://isl.gforge.inria.fr/)
Name=isl
Version=0.19
BuildDeps=(gmp)
Supplies=(http://isl.gforge.inria.fr/isl-$Version.tar.xz)

Build()
{
    ./configure --prefix=/usr --disable-static

    make
    make install
}
