#!/bin/bash

Title="6.63. Less-530"
Home=(http://www.greenwoodsoftware.com/less/ https://www.gnu.org/software/less/)
Name=Less
Version=530
Supplies=(https://ftpmirror.gnu.org/gnu/less/less-$Version.tar.gz)

Build ()
{
    ./configure --prefix=/usr --sysconfdir=/etc

    bash -l

    make
    make install
}
