#!/bin/bash

Title="Less"
Home=(http://www.greenwoodsoftware.com/less/ https://www.gnu.org/software/less/)
Name=less
Version=530
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.gz)

Build ()
{
    ./configure --prefix=/usr --sysconfdir=/etc

    make
    make install
}
