#!/bin/bash

Title="LibArchive"
Home=" http://www.libarchive.org/"
Name=LibArchive
Version=3.3.2
ToolDeps=()
BuildDeps=(LibLZO)
RunDeps=()
Supplies=(http://www.libarchive.org/downloads/libarchive-$Version.tar.gz)

Build()
{
    ./configure --prefix=/usr --disable-static

    make
    #make check
    make install
}
