#!/bin/bash

Title="LibArchive"
Home=" http://www.libarchive.org/"
Name=libarchive
Version=3.3.2
BuildDeps=(lzo)
Supplies=(http://www.libarchive.org/downloads/libarchive-$Version.tar.gz)

Build()
{
    ./configure --prefix=/usr --disable-static

    make
    make install
}
