#!/bin/bash

Title="LibIcu"
Home="http://site.icu-project.org/"
Name=LibIcu
Version=61.1
BuildIn=source
BuildDeps=()
RunDeps=()
Supplies=("http://download.icu-project.org/files/icu4c/61.1/icu4c-61_1-src.tgz")

Build()
{
    ./configure --prefix=/usr

    make
    make doc

    make install
    make install-doc
}
