#!/bin/bash

Title="LibIcu"
Name=LibIcu
Version=60.2
BuildIn=source
Supplies=(http://download.icu-project.org/files/icu4c/60.2/icu4c-60_2-src.tgz)

Build()
{
    ./configure --prefix=/usr

    make
    make doc

    make install
    make install-doc
}
