#!/bin/bash

Title="Lib-MPFR"
Home="http://www.mpfr.org/"
Name=LibMPFR
Version=4.0.1
BuildDeps=()
RunDeps=()
Supplies=(https://ftpmirror.gnu.org/gnu/mpfr/mpfr-$Version.tar.xz)

Build()
{
    ./configure \
        --prefix=/usr           \
        --disable-nls           \
        --disable-static        \
        --enable-thread-safe

    make
    make html
    #make check
    make install
    make install-html
}
