#!/bin/bash

Title="Lib-Readline"
Home=(https://tiswww.cwru.edu/php/chet/readline/rltop.html)
Name=LibReadline
Version=7.0
ToolDeps=()
BuildDeps=()
RunDeps=()
Supplies=(https://ftpmirror.gnu.org/gnu/readline/readline-$Version.tar.gz)

Build()
{
    ./configure \
        --prefix=/usr       \
        --disable-nls       \
        --disable-static

    make
    make install

    install -v -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline
}
