#!/bin/bash

Title="Lib-Readline"
Home=(https://tiswww.cwru.edu/php/chet/readline/rltop.html)
Name=LibReadline
Version=7.0
ToolDeps=()
BuildDeps=()
RunDeps=()
Supplies=(https://ftpmirror.gnu.org/gnu/readline/readline-$Version.tar.gz)

Build()
{
    # Reinstalling Readline will cause the old libraries to be moved to <libraryname>.old.
    # While this is normally not a problem, in some cases it can trigger a linking bug in ldconfig.#
    # This can be avoided by issuing the following two seds:
    sed -i '/MV.*old/d' Makefile.in
    sed -i '/{OLDSUFF}/c:' support/shlib-install

    ./configure \
        --prefix=/usr       \
        --disable-static

    make
    make install

    install -v -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline
}
