#!/bin/bash

Title="Libtool"
Home=(https://www.gnu.org/software/libtool/)
Name=Libtool
Version=2.4.6
Supplies=(https://ftpmirror.gnu.org/gnu/libtool/libtool-$Version.tar.xz)

Build()
{
    ./configure --prefix=/usr --disable-nls

    make
    make install
}
