#!/bin/bash

Title="GNU Libtool"
Home=(https://www.gnu.org/software/libtool/)
Name=libtool
Version=2.4.6
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.xz)

Build()
{
    ./configure --prefix=/usr --disable-nls

    make
    make install
}
