#!/bin/bash

Title="LibUv"
Home=(https://github.com/libuv/libuv/wiki http://docs.libuv.org/en/v1.x/)
Name=libuv
Version=1.20.3
Supplies=(https://dist.libuv.org/dist/v$Version/libuv-v$Version.tar.gz)

Build()
{
    sh autogen.sh
    ./configure --prefix=/usr --disable-static

    make
    make install
}
