#!/bin/bash

Title="Linux headers"
Home=(https://www.kernel.org/)
Name=linux-headers
Version=4.15.3
Supplies=(none)

Build()
{
    tar --verbose --extract --directory=/ --file /Data/Variable/Store/Tools/linux-headers-4.15.3/Files.tar.xz
}
