#!/bin/bash

Title="LZip"
Home=(https://www.nongnu.org/lzip/)
Name=LZip
Version=1.20
Supplies=(http://download.savannah.gnu.org/releases/lzip/lzip-$Version.tar.gz)

Build()
{
    ./configure --prefix=/usr

    make
    #make check
    make install
}
