#!/bin/bash

Title="LZO"
Home=(http://www.oberhumer.com/opensource/lzo/)
Name=luo
Version=2.10
Supplies=(http://www.oberhumer.com/opensource/lzo/download/lzo-$Version.tar.gz)

Build()
{
    ./configure --prefix=/usr       \
                --disable-nls       \
                --enable-shared     \
                --disable-static

    make
    make install
}
