#!/bin/bash (source-only)

Title="M4"
Home="https://www.gnu.org/software/m4/"
Name=m4
Version=1.4.18
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.xz)

Build() 
{
    ./configure --prefix=/usr
    make
    make install
}
