#!/bin/bash

Title="GNU mpc"
Home=(http://www.multiprecision.org/mpc/)
Name=mpc
Version=1.1.0
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.gz)

Build()
{
    ./configure \
        --prefix=/usr       \
        --disable-nls       \
        --disable-static

    make
    make html
    make install
    make install-html
}
