#!/bin/bash

Title="The GNU MPFR Library"
Home="http://www.mpfr.org/"
Name=mpfr
Version=4.0.1
BuildDeps=()
RunDeps=()
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.xz)

Build()
{
    ./configure \
        --prefix=/usr           \
        --disable-nls           \
        --disable-static        \
        --enable-thread-safe

    make
    make html
    make install
    make install-html
}
