#!/bin/bash

Title="GNU nano"
Home="https://www.nano-editor.org/"
Name=nano
Version=2.9.7
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.xz)

Build()
{
    ./configure \
        --prefix=/usr       \
        --disable-nls       \
        --sysconfdir=/etc   \
        --enable-utf8

    make
    make install
    install -v -m644 doc/{nano.html,sample.nanorc} /usr/share/doc/nano
}
