#!/bin/bash

Title="NCurses"
Home=(https://invisible-island.net/ncurses/)
Name=NCurses
Version=6.1
ToolDeps=()
BuildDeps=()
Supplies=(https://ftpmirror.gnu.org/gnu/ncurses/ncurses-$Version.tar.gz)

Build()
{
    # Don't install a static library that is not handled by configure: 
    sed -i '/LIBTOOL_INSTALL/d' c++/Makefile.in


    ./configure --prefix=/usr           \
                --disable-nls           \
                --mandir=/usr/share/man \
                --with-shared           \
                --without-debug         \
                --without-normal        \
                --enable-pc-files       \
                --enable-widec

    make

    make install

    for lib in ncurses form panel menu ; do
        rm -vf                    /usr/lib/lib${lib}.so
        echo "INPUT(-l${lib}w)" > /usr/lib/lib${lib}.so
        ln -sfv ${lib}w.pc        /usr/lib/pkgconfig/${lib}.pc
    done

    rm -vf                     /usr/lib/libcursesw.so
    echo "INPUT(-lncursesw)" > /usr/lib/libcursesw.so
    ln -sfv libncurses.so      /usr/lib/libcurses.so

    mkdir -v       /usr/share/doc/ncurses
    cp -v -R doc/* /usr/share/doc/ncurses
}
