#!/bin/bash (source-only)

Title="GNU Patch"
Home="https://www.gnu.org/software/patch/"
Name=patch
Version=2.7.6
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.gz)

Build() 
{
    ./configure --prefix=/usr

    make
    make install
}
