#!/bin/bash (source-only)

Title="Perl"
Home=(https://www.perl.org/)
Name=perl
Version=5.26.1
BuildDeps=(zlib bzip2)
Supplies=(http://www.cpan.org/src/${Version:0:1}.0/perl-$Version.tar.xz)

Build() 
{
    export BUILD_ZLIB=False
    export BUILD_BZIP2=0

    sh Configure -des -Dprefix=/usr                 \
                      -Dvendorprefix=/usr           \
                      -Dman1dir=/usr/share/man/man1 \
                      -Dman3dir=/usr/share/man/man3 \
                      -Dpager="/usr/bin/less -isR"  \
                      -Duseshrplib                  \
                      -Dusethreads
    make
    make install
}
