#!/bin/bash (source-only)

Title="6.41. XML::Parser-2.44"
Home=(http://search.cpan.org/~toddr/XML-Parser/Parser.pm)
Name=perl-xml-parser
Version=2.44
Supplies=(http://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz)

Build ()
{
    perl Makefile.PL
    make
    make install
}
