#!/bin/bash

Title="PkgConfig"
Home="https://www.freedesktop.org/wiki/Software/pkg-config/"
Name=pkg-config
Version=0.29.2
Supplies=(https://pkg-config.freedesktop.org/releases/pkg-config-$Version.tar.gz)

Build()
{
    ./configure \
        --prefix=/usr           \
        --with-internal-glib    \
        --disable-host-tool
    
    make
    make install
}
