#!/bin/bash

Title="PkgConfig"
Home="https://www.freedesktop.org/wiki/Software/pkg-config/"
Name=PkgConfig
Version=0.29.2
ToolDeps=()
BuildDeps=()
RunDeps=()
Supplies=(https://pkg-config.freedesktop.org/releases/pkg-config-$Version.tar.gz)

Build()
{
    #bash -l; exit

    ./configure \
        --prefix=/usr           \
        --with-internal-glib    \
        --disable-host-tool
    
    make
    #make check
    make install
}
