#!/bin/bash

Title="PSMisc"
Home=(http://psmisc.sourceforge.net/)
Name=psmisc
Version=23.1
Supplies=(https://sourceforge.net/projects/$Name/files/$Name/$Name-$Version.tar.xz)

Build()
{
    ./configure --prefix=/usr --disable-nls

    make
    make install
}
