#!/bin/bash

Title="PsMisc"
Home=(http://psmisc.sourceforge.net/)
Name=PsMisc
Version=23.1
ToolDeps=()
BuildDeps=()
RunDeps=()
Supplies=(https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-$Version.tar.xz)

Build()
{
    ./configure --prefix=/usr --disable-nls

    make
    make install
}
