#!/bin/bash (source-only)

Title="Python2"
Home=(https://www.python.org/)
Name=Python2
Version=2.7.15
Supplies=(https://www.python.org/ftp/python/$Version/Python-$Version.tar.xz)

Build() 
{
    ./configure --prefix=/usr
    make

    make install
}
