#!/bin/bash (source-only)

Title="Python3"
Home=(https://www.python.org/)
Name=Python3
Version=3.6.5
BuildDeps=(LibExpat LibFfi)
Supplies=(https://www.python.org/ftp/python/$Version/Python-$Version.tar.xz)

Build() 
{
    CXX="/usr/bin/g++" ./configure \
        --prefix=/usr       \
        --enable-shared     \
        --with-system-expat \
        --with-system-ffi   \
        --with-ensurepip=yes

    make

    make install
    chmod -v 755 /usr/lib/libpython3.6m.so
    chmod -v 755 /usr/lib/libpython3.so
}
