#!/bin/bash (source-only)

Title="Python2"
Name=Python2
Version=2.7.14
Supplies=(
    https://www.python.org/ftp/python/$Version/Python-$Version.tar.xz 
)

Build() 
{
    ./configure --prefix=/usr
    make

    make install
}
