#!/bin/bash

Title="Sed"
Home=(http://sed.sourceforge.net/ https://www.gnu.org/software/sed/)
Name=sed
Version=4.5
Supplies=(https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.xz)

Build()
{
    ./configure \
        --prefix=/usr   \
        --disable-nls

    make
    make html
    make install
    install -v -d -m755           /usr/share/doc/sed
    install -v -m644 doc/sed.html /usr/share/doc/sed
}
