#!/bin/bash

Title="STrace"
Home=(https://strace.io/)
Name=STrace
Version=4.22
Supplies=(https://strace.io/files/$Version/strace-$Version.tar.xz)

Build()
{
    ./configure --prefix=/usr

    make
    make install
}
