#!/bin/bash (source-only)

Title="Which"
Name=Which
Version=2.21
Supplies=(
     https://ftp.gnu.org/gnu/which/which-$Version.tar.gz
)

Build() 
{
    ./configure --prefix=/usr
    make

    make install
}
