#!/bin/bash

Title="XZ Utils"
Home=(https://tukaani.org/xz/)
Name=xz-utils
Version=5.2.4
Supplies=(https://tukaani.org/xz/xz-$Version.tar.xz)

Build()
{
    ./configure --prefix=/usr       \
                --disable-nls       \
                --disable-static

    make
    make install
}
