#!/bin/bash

Title="Lib ZLib"
Home=(https://zlib.net/)
Name=zlib
Version=1.2.11
Supplies=(https://zlib.net/$Name-$Version.tar.xz)

Build()
{
    ./configure --prefix=/usr

    make
    make install
}
