#!/usr/bin/env pwsh (source-only)

$McTitle='GCC, the GNU Compiler Collection'
$McDesription=@'
The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, and Go, as
well as libraries for these languages (libstdc++,...). GCC was originally written as the compiler
for the GNU operating system. The GNU system was developed to be 100% free software, free in the
sense that it respects the user's freedom.
'@

$McName='gcc'
$McVersion='8.1.0'

$McHome=@("https://www.gnu.org/software/gcc/")
$McBuildDeps=@("isl", "gmp", "mpfr", "mpc", "zlib")
$McUpstream="https://ftpmirror.gnu.org/gnu/$McName/$McName-$McVersion/$McName-$McVersion.tar.xz"
