#!/bin/bash
EnterWorldOfPogo Boots
NeverInChroot

pogo boots clean

for recipe in {504..534}; do
    pogo boots download $recipe
done
for recipe in {504..534}; do
    pogo boots build $recipe
    pogo boots harvest $recipe
    pogo boots rollout $recipe
done
