#!/bin/bash (source-only)
set -euo pipefail
#IFS=$'\n\t'

[[ -z ${_pogoConfigIncluded:-} ]] || exit
_pogoConfigIncluded=true

if [[ -n "${POGO_CHROOT:-}" ]]; then
    InChroot() { return 0; }
else
    InChroot() { return 1; }
fi

NeverInChroot ()
{
    InChroot && Fatal "never ever call this in a chroot"
    true
}

OnlyInChroot ()
{
    InChroot || Fatal "only call this in a chroot"
    true
}

PogoVolume=/Pogo

PogoData=/Data
PogoPrograms=/Programs
PogoSystem=/System

PogoCompile=$PogoData/Compile
PogoSources=$PogoCompile/Sources
PogoBuild=$PogoCompile/Build
PogoRoots=$PogoCompile/Roots
PogoLfs=$PogoCompile/Lfs
PogoTools=$PogoLfs/tools

PogoVariable=$PogoData/Variable
PogoArchives=$PogoVariable/Archives
PogoDownloads=$PogoVariable/Downloads
PogoStore=$PogoVariable/Store

PogoIndex=$PogoSystem/Index

Recipes_Home=/LiFo/Recipes

Boots_Collection=Boots
Boots_Root="$PogoRoots/$Boots_Collection"
Boots_Store="$PogoStore/$Boots_Collection"
Boots_Build="$PogoBuild/$Boots_Collection"

Tools_Collection=Tools
Tools_Root="$PogoRoots/$Tools_Collection"
Tools_Store="$PogoStore/$Tools_Collection"
Tools_Build="$PogoBuild/$Tools_Collection"

Core_Collection=Core
Core_Root="$PogoRoots/$Core_Collection"
Core_Store="$PogoStore/$Core_Collection"
Core_Build="$PogoBuild/$Core_Collection"

declare Current_Collection
declare Current_Root
declare Current_Store
declare Current_Build

Build_Collections=(
    "$Boots_Collection"
    "$Tools_Collection"
    "$Core_Collection"
)

Recipes_Collections=(
    "$Boots_Collection"
    "$Tools_Collection"
    "$Core_Collection"
)

#if [[ -n "${1-}" ]]; then
#    echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#    echo "Selection: $1"
#    echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#fi

Fatal ()
{
    local prefix
    case $0 in
        */pogo) prefix='' ;;
        *) prefix="pogo " ;;
    esac
        
    echo "${prefix}${0##*/}:" "$@" 1>&2
    exit 127
}

InfoExit ()
{
    local prefix
    case $0 in
        */pogo) ;;
        *) prefix="pogo " ;;
    esac
        
    echo "${prefix}${0##*/}: $1"

    exit
}

Trace ()
{
    echo "$1" >/dev/console
}

PogoExec ()
{
    [[ -n "$1" ]] || Fatal "no argument given"
    script="$Pogos/$1"
    [[ -e "$script" ]] || Fatal "unknown function '$1'"
    shift
    $script "$@"
}

EnterWorldOfPogo ()
{
    source "$Pogos/PogoConfig" "${1-}"
}

# export function for convenience
declare -F -x EnterWorldOfPogo

verbose=--verbose

source $Pogos/.pogoFunctions
source $Pogos/.recipeFunctions
source $Pogos/.buildFunctions
