#!/bin/bash -eu
EnterWorldOfPogo


#_recipeSource "${1:-}"
#exit

RecipeSource "${1:-}"

#exit

declare -p Recipe_Collection
declare -p Recipe_Token
declare -p Recipe_Tag

declare -p Recipe_Title
declare -p Recipe_Name
declare -p Recipe_Version
declare -p Recipe_Supplies

#for supply in "${Recipe_Supplies[@]}"; do
#    echo "supply: $supply"
#    already=$(basename $supply)
#    find $PogoArchives $PogoDownloads -maxdepth 1 -name "$already" | head --lines=1 | while read already; do
#        echo "already available: $already"
#    done
#done
