#!/bin/bash -eu
EnterWorldOfPogo Tools
NeverInChroot

RemoveDir $Tools_Root
RemoveDir $Tools_Build

upto="$1"

for recipe in {607..677}; do

    Build_Setup tools $recipe

    if [[ "$recipe" == "$upto" ]]; then
        pogo tools build   $recipe  | sed -u -e 's/^/BUILD  : /'   | tee "$Store_Logs/Build"
        pogo tools harvest $recipe  | sed -u -e 's/^/HARVEST: /'   | tee "$Store_Logs/Harvest"
        less $Store_FilesBom
        exit
    else
        pogo tools rollout $recipe  | sed -u -e 's/^/ROLLOUT: /'   | tee "$Store_Logs/Rollout"
    fi
done
