#!/bin/bash
EnterWorldOfPogo Tools
NeverInChroot

set

exit

pogo tools clean

for recipe in {607..677}; do
    pogo tools download $recipe
done
for recipe in {607..677}; do
    pogo tools build $recipe
    pogo tools harvest $recipe
    pogo tools rollout $recipe
done
