#!/bin/bash

Name=Binutils
Title='5.4. Binutils-2.30 - Pass 1'
Version=2.30
Supplies=(http://ftp.gnu.org/gnu/binutils/binutils-2.30.tar.xz)
BuildIn=build

Configure() {
    ../configure \
        --prefix=/tools             \
        --with-sysroot=$LFS         \
        --with-lib-path=/tools/lib  \
        --target=$LFS_TGT           \
        --disable-nls               \
        --disable-werror
}

Build() {
    make
}

Install() {
    make install
}
