#!/bin/bash

Title="5.5. GCC-7.3.0 - Pass 1"
Name=Gcc1
Version=7.3.0
Supplies=(
    http://ftp.gnu.org/gnu/gcc/gcc-7.3.0/gcc-7.3.0.tar.xz
    http://www.mpfr.org/mpfr-4.0.1/mpfr-4.0.1.tar.xz
    http://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.xz
    https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz
)
BuildIn=build

Prepare()
{
    ln --verbose --symbolic ../mpfr-4.0.1 mpfr
    ln --verbose --symbolic ../gmp-6.1.2 gmp
    ln --verbose --symbolic ../mpc-1.1.0 mpc

    for file in gcc/config/{linux,i386/linux{,64}}.h
    do
        cp -uv $file{,.orig}
        sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \
            -e 's@/usr@/tools@g' $file.orig > $file
        echo '
#undef STANDARD_STARTFILE_PREFIX_1
#undef STANDARD_STARTFILE_PREFIX_2
#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"
#define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
        touch $file.orig
    done

    sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64
}

Configure()
{
    ../configure                                       \
        --target=$LFS_TGT                              \
        --prefix=/tools                                \
        --with-glibc-version=2.11                      \
        --with-sysroot=$LFS                            \
        --with-newlib                                  \
        --without-headers                              \
        --with-local-prefix=/tools                     \
        --with-native-system-header-dir=/tools/include \
        --disable-nls                                  \
        --disable-shared                               \
        --disable-multilib                             \
        --disable-decimal-float                        \
        --disable-threads                              \
        --disable-libatomic                            \
        --disable-libgomp                              \
        --disable-libmpx                               \
        --disable-libquadmath                          \
        --disable-libssp                               \
        --disable-libvtv                               \
        --disable-libstdcxx                            \
        --enable-languages=c,c++
}

Build()
{
    make
}

Install()
{
    make install
}
