#!/bin/bash

Title="5.9. Binutils-2.30 - Pass 2"
Name=Binutils2
Version=2.30
Supplies=(http://ftp.gnu.org/gnu/binutils/binutils-2.30.tar.xz)
BuildIn=build

Configure() {
    CC=$LFS_TGT-gcc                 \
    AR=$LFS_TGT-ar                  \
    RANLIB=$LFS_TGT-ranlib          \
    ../configure                    \
        --prefix=/tools             \
        --disable-nls               \
        --disable-werror            \
        --with-lib-path=/tools/lib  \
        --with-sysroot
}

Build() {
    make
}

Install() {
    make install
    make -C ld clean
    make -C ld LIB_PATH=/usr/lib:/lib
    cp -v ld/ld-new /tools/bin
}
