#!/bin/bash

Title="5.12. Expect-5.45.4"
Name=Expect
Version=5.45.4
Supplies=(http://prdownloads.sourceforge.net/expect/expect5.45.4.tar.gz)

Configure()
{
    cp -v configure{,.orig}
    sed 's:/usr/local/bin:/bin:' configure.orig > configure

    ./configure \
        --prefix=/tools         \
        --with-tcl=/tools/lib   \
        --with-tclinclude=/tools/include
}

Build() 
{
    make -j4
}

Install() 
{
    make SCRIPTS="" install
}
