#!/bin/bash

Title="5.13. DejaGNU-1.6.1"
Name=DejaGNU
Version=1.6.1
Supplies=(http://ftp.gnu.org/gnu/dejagnu/dejagnu-1.6.1.tar.gz)

Build()
{
    ./configure --prefix=/tools

    make install
    make check
}
