#!/bin/bash

Title="5.14. M4-1.4.18"
Name=m4
Version=1.4.18
Supplies=(http://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.xz)

Configure() {
    ./configure --prefix=/tools
}

Build() {
    make
}

Install() {
    make install
}
