#!/bin/bash

Title="5.15. Ncurses-6.1"
Name=NCurses
Version=6.1
Supplies=(http://ftp.gnu.org/gnu/ncurses/ncurses-6.1.tar.gz)

Build() 
{
    sed -i s/mawk// configure

    ./configure \
        --prefix=/tools \
        --with-shared   \
        --without-debug \
        --without-ada   \
        --enable-widec  \
        --enable-overwrite

    make

    make install
}
