#!/bin/bash

Title="5.17. Bison-3.0.4"
Name=Bison
Version=3.0.4
Supplies=(http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.xz)

Configure() 
{
    ./configure --prefix=/tools
}

Build() 
{
    make -j8
}

Install() 
{
    make install
}
