#!/bin/bash

Title="5.17. Bison-3.0.4"
Name=bison
Version=3.0.4
Supplies=(http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.xz)

Configure() {
    ./configure --prefix=/tools
}

Build() {
    make
}

Install() {
    make install
}
