#!/bin/bash

Title="5.19. Coreutils-8.29"
Name=Coreutils
Version=8.29
Supplies=(http://ftp.gnu.org/gnu/coreutils/coreutils-8.29.tar.xz)

Configure() 
{
    ./configure --prefix=/tools --enable-install-program=hostname
}

Build() 
{
    make -j8
}

Install() 
{
    make install
}
