#!/bin/bash

Title="5.20. Diffutils-3.6"
Name=Diffutils
Version=3.6
Supplies=(http://ftp.gnu.org/gnu/diffutils/diffutils-3.6.tar.xz)

Configure() 
{
    ./configure --prefix=/tools
}

Build() 
{
    make
}

Install() 
{
    make install
}
