#!/bin/bash

Title="5.22. Findutils-4.6.0"
Name=Findutils
Version=4.6.0
Supplies=(http://ftp.gnu.org/gnu/findutils/findutils-4.6.0.tar.gz)

Configure() 
{
    ./configure --prefix=/tools
}

Build() 
{
    make -j8
}

Install() 
{
    make install
}
