#!/bin/bash

Title="5.23. Gawk-4.2.0"
Name=gawk
Version=4.2.0
Supplies=(http://ftp.gnu.org/gnu/gawk/gawk-4.2.0.tar.xz)

Configure() {
    ./configure --prefix=/tools
}

Build() {
    make
}

Install() {
    make install
}
