#!/bin/bash

Title="5.29. Perl-5.26.1"
Name=Perl
Version=5.26.1
Supplies=(http://www.cpan.org/src/5.0/perl-5.26.1.tar.xz)

Configure() 
{
    sh Configure -des -Dprefix=/tools -Dlibs=-lm
}

Build() 
{
    make -j8
}

Install() 
{
    cp -v perl cpan/podlators/scripts/pod2man /tools/bin
    mkdir -pv /tools/lib/perl5/5.26.1
    cp -Rv lib/* /tools/lib/perl5/5.26.1
}
