#!/bin/bash

Title="5.30. Sed-4.4"
Name=Sed
Version=4.4
Supplies=(http://ftp.gnu.org/gnu/sed/sed-4.4.tar.xz)

Configure() 
{
    ./configure --prefix=/tools
}

Build() 
{
    make
}

Install() 
{
    make install
}
