#!/bin/bash
#
# Build $LFS/tools bootstrapping tools
#

if [ ! $(whoami) == "lfs" ]; then
    echo "Please run as lfs!"
    exit 1
fi

function provide {
    stem=$1
    arch=$2
    cd $LFS/sources
    rm -rvf $stem
    tar xvf $arch
    cd $stem
    pwd
}

case "$1" in
    000)
        [ -d $LFS/tools ] && rm -rfv $LFS/tools
        [ -d $LFS/tools ] || mkdir $LFS/tools

        ;;












    53x)
        echo "5.35. Stripping"

        cp -vf /tools/bin/strip /tools

        /tools/strip --strip-debug /tools/lib/*
        /tools/strip --strip-unneeded /tools/{,s}bin/*

        rm -v /tools/strip

        rm -rfv /tools/{,share}/{info,man,doc}

        find /tools/{lib,libexec} -name \*.la -delete

        ;;

esac