#!/bin/bash
#
# Build $LFS/tools bootstrapping tools
#

if [ ! $(whoami) == "lfs" ]; then
    echo "Please run as lfs!"
    exit 1
fi

function provide {
    stem=$1
    arch=$2
    cd $LFS/sources
    rm -rvf $stem
    tar xvf $arch
    cd $stem
    pwd
}

case "$1" in
    000)
        [ -d $LFS/tools ] && rm -rfv $LFS/tools
        [ -d $LFS/tools ] || mkdir $LFS/tools

        ;;

    504)
        echo "5.4. Binutils-2.30 - Pass 1"
        # http://ftp.gnu.org/gnu/binutils/binutils-2.30.tar.xz

        provide binutils-2.30 binutils-2.30.tar.xz

        mkdir -v build
        cd       build

        ../configure --prefix=/tools    \
             --with-sysroot=$LFS        \
             --with-lib-path=/tools/lib \
             --target=$LFS_TGT          \
             --disable-nls              \
             --disable-werror

        make

        case $(uname -m) in
            x86_64) mkdir -v /tools/lib && ln -sv lib /tools/lib64 ;;
        esac

        make install

        ;;

    505)
        echo "5.5. GCC-7.3.0 - Pass 1"
        # http://ftp.gnu.org/gnu/gcc/gcc-7.3.0/gcc-7.3.0.tar.xz

        provide gcc-7.3.0 gcc-7.3.0.tar.xz

        tar -xf ../mpfr-4.0.1.tar.xz
        mv -v mpfr-4.0.1 mpfr
        tar -xf ../gmp-6.1.2.tar.xz
        mv -v gmp-6.1.2 gmp
        tar -xf ../mpc-1.1.0.tar.gz
        mv -v mpc-1.1.0 mpc

        for file in gcc/config/{linux,i386/linux{,64}}.h
        do
            cp -uv $file{,.orig}
            sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \
                -e 's@/usr@/tools@g' $file.orig > $file
            echo '
#undef STANDARD_STARTFILE_PREFIX_1
#undef STANDARD_STARTFILE_PREFIX_2
#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"
#define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
            touch $file.orig
        done

        case $(uname -m) in
            x86_64)
                sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64
                ;;
        esac

        mkdir -v build
        cd       build

        ../configure                                       \
            --target=$LFS_TGT                              \
            --prefix=/tools                                \
            --with-glibc-version=2.11                      \
            --with-sysroot=$LFS                            \
            --with-newlib                                  \
            --without-headers                              \
            --with-local-prefix=/tools                     \
            --with-native-system-header-dir=/tools/include \
            --disable-nls                                  \
            --disable-shared                               \
            --disable-multilib                             \
            --disable-decimal-float                        \
            --disable-threads                              \
            --disable-libatomic                            \
            --disable-libgomp                              \
            --disable-libmpx                               \
            --disable-libquadmath                          \
            --disable-libssp                               \
            --disable-libvtv                               \
            --disable-libstdcxx                            \
            --enable-languages=c,c++
    
        make

        make install

        ;;

    506)
        echo "5.6. Linux-4.15.3 API Headers"
        # https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.15.3.tar.xz
        
        provide linux-4.15.3 linux-4.15.3.tar.xz

        make mrproper

        make INSTALL_HDR_PATH=dest headers_install
        cp -rv dest/include/* /tools/include

        ;;

    507)
        echo "5.7. Glibc-2.27"
        # http://ftp.gnu.org/gnu/glibc/glibc-2.27.tar.xz

        provide glibc-2.27 glibc-2.27.tar.xz

        mkdir -v build
        cd       build

        ../configure                            \
            --prefix=/tools                     \
            --host=$LFS_TGT                     \
            --build=$(../scripts/config.guess)  \
            --enable-kernel=3.2                 \
            --with-headers=/tools/include       \
            libc_cv_forced_unwind=yes           \
            libc_cv_c_cleanup=yes

        make

        make install

        ;;

    508)
        echo "5.8. Libstdc++-7.3.0"
        # http://ftp.gnu.org/gnu/gcc/gcc-7.3.0/gcc-7.3.0.tar.xz

        provide gcc-7.3.0 gcc-7.3.0.tar.xz

        mkdir -v build
        cd       build

        ../libstdc++-v3/configure           \
            --host=$LFS_TGT                 \
            --prefix=/tools                 \
            --disable-multilib              \
            --disable-nls                   \
            --disable-libstdcxx-threads     \
            --disable-libstdcxx-pch         \
            --with-gxx-include-dir=/tools/$LFS_TGT/include/c++/7.3.0

        make

        make install

        ;;

    509)
        echo "5.9. Binutils-2.30 - Pass 2"
        # http://ftp.gnu.org/gnu/binutils/binutils-2.30.tar.xz

        provide binutils-2.30 binutils-2.30.tar.xz

        mkdir -v build
        cd       build

        CC=$LFS_TGT-gcc                 \
        AR=$LFS_TGT-ar                  \
        RANLIB=$LFS_TGT-ranlib          \
        ../configure                    \
            --prefix=/tools             \
            --disable-nls               \
            --disable-werror            \
            --with-lib-path=/tools/lib  \
            --with-sysroot

        make

        make install

        make -C ld clean
        make -C ld LIB_PATH=/usr/lib:/lib
        cp -v ld/ld-new /tools/bin

        ;;

    510)
        echo "5.10. GCC-7.3.0 - Pass 2"
        # http://ftp.gnu.org/gnu/gcc/gcc-7.3.0/gcc-7.3.0.tar.xz

        provide gcc-7.3.0 gcc-7.3.0.tar.xz

        cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
            `dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/include-fixed/limits.h

        for file in gcc/config/{linux,i386/linux{,64}}.h
        do
            cp -uv $file{,.orig}
            sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \
                -e 's@/usr@/tools@g' $file.orig > $file
            echo '
#undef STANDARD_STARTFILE_PREFIX_1
#undef STANDARD_STARTFILE_PREFIX_2
#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"
#define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
            touch $file.orig
        done

        case $(uname -m) in
            x86_64)
                sed -e '/m64=/s/lib64/lib/' \
                    -i.orig gcc/config/i386/t-linux64
                ;;
        esac

        tar -xf ../mpfr-4.0.1.tar.xz
        mv -v mpfr-4.0.1 mpfr
        tar -xf ../gmp-6.1.2.tar.xz
        mv -v gmp-6.1.2 gmp
        tar -xf ../mpc-1.1.0.tar.gz
        mv -v mpc-1.1.0 mpc

        mkdir -v build
        cd       build

        CC=$LFS_TGT-gcc                                     \
        CXX=$LFS_TGT-g++                                    \
        AR=$LFS_TGT-ar                                      \
        RANLIB=$LFS_TGT-ranlib                              \
        ../configure                                        \
            --prefix=/tools                                 \
            --with-local-prefix=/tools                      \
            --with-native-system-header-dir=/tools/include  \
            --enable-languages=c,c++                        \
            --disable-libstdcxx-pch                         \
            --disable-multilib                              \
            --disable-bootstrap                             \
            --disable-libgomp

        make

        make install

        ln -sv gcc /tools/bin/cc

        ;;

    511)
        echo "5.11. Tcl-core-8.6.8"
        # https://downloads.sourceforge.net/tcl/tcl8.6.8-src.tar.gz

        provide tcl8.6.8 tcl8.6.8-src.tar.gz

        cd unix
        ./configure --prefix=/tools

        make

        # not mandatory
        #TZ=UTC make test

        make install

        chmod -v u+w /tools/lib/libtcl8.6.so

        make install-private-headers

        ln -sv tclsh8.6 /tools/bin/tclsh

        ;;

    512)
        echo "5.12. Expect-5.45.4"
        # http://prdownloads.sourceforge.net/expect/expect5.45.4.tar.gz

        provide expect5.45.4 expect5.45.4.tar.gz

        cp -v configure{,.orig}
        sed 's:/usr/local/bin:/bin:' configure.orig > configure

        ./configure --prefix=/tools     \
            --with-tcl=/tools/lib       \
            --with-tclinclude=/tools/include

        make

        # not mandatory
        #make test

        make SCRIPTS="" install

        ;;

    513)
        echo "5.13. DejaGNU-1.6.1"
        # http://ftp.gnu.org/gnu/dejagnu/dejagnu-1.6.1.tar.gz

        provide dejagnu-1.6.1 dejagnu-1.6.1.tar.gz

        ./configure --prefix=/tools

        make install

        make check

        ;;

    514)
        echo "5.14. M4-1.4.18"
        # http://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.xz

        provide m4-1.4.18 m4-1.4.18.tar.xz

        ./configure --prefix=/tools

        make

        # not mandatory
        #make check

        make install

        ;;

    515)
        echo "5.15. Ncurses-6.1"
        # http://ftp.gnu.org/gnu//ncurses/ncurses-6.1.tar.gz

        provide ncurses-6.1 ncurses-6.1.tar.gz

        sed -i s/mawk// configure

        ./configure --prefix=/tools \
                    --with-shared   \
                    --without-debug \
                    --without-ada   \
                    --enable-widec  \
                    --enable-overwrite

        make

        make install

        ;;

    516)
        echo "5.16. Bash-4.4.18"
        # http://ftp.gnu.org/gnu/bash/bash-4.4.18.tar.gz

        provide bash-4.4.18 bash-4.4.18.tar.gz

        ./configure --prefix=/tools --without-bash-malloc

        make

        # not mandatory
        #make tests

        make install

        ln -sv bash /tools/bin/sh

        ;;

    517)
        echo "5.17. Bison-3.0.4"
        # http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.xz

        provide bison-3.0.4 bison-3.0.4.tar.xz

        ./configure --prefix=/tools

        make

        # not mandatory
        #make check

        make install

        ;;

    518)
        echo "5.18. Bzip2-1.0.6"
        # http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz

        provide bzip2-1.0.6 bzip2-1.0.6.tar.gz

        make

        make PREFIX=/tools install

        ;;

    519)
        echo "5.19. Coreutils-8.29"
        # http://ftp.gnu.org/gnu/coreutils/coreutils-8.29.tar.xz

        provide coreutils-8.29 coreutils-8.29.tar.xz

        ./configure --prefix=/tools --enable-install-program=hostname

        make

        # not mandatory
        #make RUN_EXPENSIVE_TESTS=yes check

        make install

        ;;

    520)
        echo "5.20. Diffutils-3.6"
        # http://ftp.gnu.org/gnu/diffutils/diffutils-3.6.tar.xz

        provide diffutils-3.6 diffutils-3.6.tar.xz

        ./configure --prefix=/tools

        make

        # not mandatory
        #make check

        make install

        ;;

    521)
        echo "5.21. File-5.32"
        # ftp://ftp.astron.com/pub/file/file-5.32.tar.gz

        provide file-5.32 file-5.32.tar.gz

        ./configure --prefix=/tools

        make

        # not mandatory
        #make check

        make install

        ;;

    522)
        echo "5.22. Findutils-4.6.0"
        # http://ftp.gnu.org/gnu/findutils/findutils-4.6.0.tar.gz

        provide findutils-4.6.0 findutils-4.6.0.tar.gz

        ./configure --prefix=/tools

        make

        # not mandatory
        #make check

        make install

        ;;

    523)
        echo "5.23. Gawk-4.2.0"
        # http://ftp.gnu.org/gnu/gawk/gawk-4.2.0.tar.xz

        provide gawk-4.2.0 gawk-4.2.0.tar.xz

        ./configure --prefix=/tools

        make

        # not mandatory
        #make check

        make install

        ;;

    524)
        echo "5.24. Gettext-0.19.8.1"
        # http://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.xz

        provide gettext-0.19.8.1 gettext-0.19.8.1.tar.xz

        cd gettext-tools
        EMACS="no" ./configure --prefix=/tools --disable-shared

        make -C gnulib-lib
        make -C intl pluralx.c
        make -C src msgfmt
        make -C src msgmerge
        make -C src xgettext

        cp -v src/{msgfmt,msgmerge,xgettext} /tools/bin

        ;;

    525)
        echo "5.25. Grep-3.1"
        # http://ftp.gnu.org/gnu/grep/grep-3.1.tar.xz

        provide grep-3.1 grep-3.1.tar.xz

        ./configure --prefix=/tools

        make

        # not mandatory
        #make check

        make install

        ;;

    526)
        echo "5.26. Gzip-1.9"
        # http://ftp.gnu.org/gnu/gzip/gzip-1.9.tar.xz

        provide gzip-1.9 gzip-1.9.tar.xz

        ./configure --prefix=/tools

        make

        # not mandatory
        #make check

        make install

        ;;

    527)
        echo "5.27. Make-4.2.1"
        # http://ftp.gnu.org/gnu/make/make-4.2.1.tar.bz2

        provide make-4.2.1 make-4.2.1.tar.bz2

        sed -i '211,217 d; 219,229 d; 232 d' glob/glob.c

        ./configure --prefix=/tools --without-guile

        make

        # not mandatory
        #make check

        make install

        ;;

    528)
        echo "5.28. Patch-2.7.6"
        # http://ftp.gnu.org/gnu/patch/patch-2.7.6.tar.xz

        provide patch-2.7.6 patch-2.7.6.tar.xz

        ./configure --prefix=/tools

        make

        # not mandatory
        #make check

        make install

        ;;

    529)
        echo "5.29. Perl-5.26.1"
        # http://www.cpan.org/src/5.0/perl-5.26.1.tar.xz

        provide perl-5.26.1 perl-5.26.1.tar.xz

        sh Configure -des -Dprefix=/tools -Dlibs=-lm

        make

        cp -v perl cpan/podlators/scripts/pod2man /tools/bin
        mkdir -pv /tools/lib/perl5/5.26.1
        cp -Rv lib/* /tools/lib/perl5/5.26.1

        ;;

    530)
        echo "5.30. Sed-4.4"
        # http://ftp.gnu.org/gnu/sed/sed-4.4.tar.xz

        provide sed-4.4 sed-4.4.tar.xz

        ./configure --prefix=/tools

        make

        # not mandatory
        #make check

        make install

        ;;

    531)
        echo "5.31. Tar-1.30"
        # http://ftp.gnu.org/gnu/tar/tar-1.30.tar.xz

        provide tar-1.30 tar-1.30.tar.xz

        ./configure --prefix=/tools

        make

        # not mandatory
        #make check

        make install

        ;;

    532)
        echo "5.32. Texinfo-6.5"        
        # http://ftp.gnu.org/gnu/texinfo/texinfo-6.5.tar.xz

        provide texinfo-6.5 texinfo-6.5.tar.xz

        ./configure --prefix=/tools

        make

        # not mandatory
        #make check

        make install

        ;;

    533)
        echo "5.33. Util-linux-2.31.1"
        # https://www.kernel.org/pub/linux/utils/util-linux/v2.31/util-linux-2.31.1.tar.xz

        provide util-linux-2.31.1 util-linux-2.31.1.tar.xz

        ./configure --prefix=/tools                 \
                    --without-python                \
                    --disable-makeinstall-chown     \
                    --without-systemdsystemunitdir  \
                    --without-ncurses               \
                    PKG_CONFIG=""

        make

        make install

        ;;

    534)
        echo "5.34. Xz-5.2.3"
        # http://tukaani.org/xz/xz-5.2.3.tar.xz

        provide xz-5.2.3 xz-5.2.3.tar.xz

        ./configure --prefix=/tools

        make

        # not mandatory
        #make check

        make install

        ;;

    53x)
        echo "5.35. Stripping"

        cp -vf /tools/bin/strip /tools

        /tools/strip --strip-debug /tools/lib/*
        /tools/strip --strip-unneeded /tools/{,s}bin/*

        rm -v /tools/strip

        rm -rfv /tools/{,share}/{info,man,doc}

        find /tools/{lib,libexec} -name \*.la -delete

        ;;

esac