#!/bin/bash
#
# Setup chroot environment and execute something there
#

if [ ! $(whoami) == "root" ]; then
    echo "Please run as root!"
    exit 1
fi

export LFS=/tmp/LFS

function unmount {
    mountpoint $LFS/dev/pts &>/dev/null && umount $LFS/dev/pts
    mountpoint $LFS/dev     &>/dev/null && umount $LFS/dev
    mountpoint $LFS/proc    &>/dev/null && umount $LFS/proc
    mountpoint $LFS/sys     &>/dev/null && umount $LFS/sys
    mountpoint $LFS/run     &>/dev/null && umount $LFS/run
    mountpoint $LFS/scripts &>/dev/null && umount $LFS/scripts
    mountpoint $LFS/tools   &>/dev/null && umount $LFS/tools
    mountpoint $LFS/sources &>/dev/null && umount $LFS/sources
}

function cleanup {
    unmount
}

trap cleanup EXIT

mkdir -p $LFS/{dev,proc,sys,run,scripts,tools,sources}

[ -c $LFS/dev/console ] || mknod -m 600 $LFS/dev/console c 5 1
[ -c $LFS/dev/null ]    || mknod -m 666 $LFS/dev/null c 1 3

unmount

#/mnt/d/Projects/LFS/8.2/scripts

mount --bind /dev $LFS/dev
mount --bind /mnt/d/Projects/LFS/8.2/scripts $LFS/scripts
mount --bind /tmp/lfs/tools $LFS/tools
mount --bind /tmp/lfs/sources $LFS/sources

mount -t devpts devpts $LFS/dev/pts -o gid=5,mode=620
mount -t proc proc $LFS/proc
mount -t sysfs sysfs $LFS/sys
mount -t tmpfs tmpfs $LFS/run

[ -h $LFS/dev/shm ] && mkdir -p $LFS$(readlink $LFS/dev/shm)

chroot "$LFS" /tools/bin/env -i \
    HOME=/root                  \
    TERM="$TERM"                \
    PS1='(lfs chroot) \u:\w\$ ' \
    PATH=/scripts:/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
    /tools/bin/bash +h -c "$@"

