#!/tools/bin/bash
#
# Build $LFS/tools bootstrapping tools
#

function provide {
    stem=$1
    arch=$2
    cd /sources
    export TEMPMOUNT=/sources/$stem
    mount -t tmpfs none $TEMPMOUNT
    tar xvf $arch
    cd $stem
    pwd
}

function cleanup {
    cd /
    mountpoint $TEMPMOUNT &>/dev/null && umount $TEMPMOUNT
}

trap cleanup EXIT

case "$1" in
    605)
        echo "6.5. Creating Directories"

        mkdir -pv /{bin,boot,etc/{opt,sysconfig},home,lib/firmware,mnt,opt}
        mkdir -pv /{media/{floppy,cdrom},sbin,srv,var}
        install -dv -m 0750 /root
        install -dv -m 1777 /tmp /var/tmp
        mkdir -pv /usr/{,local/}{bin,include,lib,sbin,src}
        mkdir -pv /usr/{,local/}share/{color,dict,doc,info,locale,man}
        mkdir -v  /usr/{,local/}share/{misc,terminfo,zoneinfo}
        mkdir -v  /usr/libexec
        mkdir -pv /usr/{,local/}share/man/man{1..8}

        case $(uname -m) in
            x86_64) mkdir -v /lib64 ;;
        esac

        mkdir -v /var/{log,mail,spool}
        ln -sv /run /var/run
        ln -sv /run/lock /var/lock
        mkdir -pv /var/{opt,cache,lib/{color,misc,locate},local}

        ;;

    606)
        echo "6.6. Creating Essential Files and Symlinks"

        ln -sv /tools/bin/{bash,cat,dd,echo,ln,pwd,rm,stty} /bin
        ln -sv /tools/bin/{install,perl} /usr/bin
        ln -sv /tools/lib/libgcc_s.so{,.1} /usr/lib
        ln -sv /tools/lib/libstdc++.{a,so{,.6}} /usr/lib
        ln -sv bash /bin/sh

        ln -sv /proc/self/mounts /etc/mtab

        cat > /etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/bin/false
daemon:x:6:6:Daemon User:/dev/null:/bin/false
messagebus:x:18:18:D-Bus Message Daemon User:/var/run/dbus:/bin/false
nobody:x:99:99:Unprivileged User:/dev/null:/bin/false
EOF

        cat > /etc/group << "EOF"
root:x:0:
bin:x:1:daemon
sys:x:2:
kmem:x:3:
tape:x:4:
tty:x:5:
daemon:x:6:
floppy:x:7:
disk:x:8:
lp:x:9:
dialout:x:10:
audio:x:11:
video:x:12:
utmp:x:13:
usb:x:14:
cdrom:x:15:
adm:x:16:
messagebus:x:18:
systemd-journal:x:23:
input:x:24:
mail:x:34:
nogroup:x:99:
users:x:999:
EOF

        touch /var/log/{btmp,lastlog,faillog,wtmp}
        chgrp -v utmp /var/log/lastlog
        chmod -v 664  /var/log/lastlog
        chmod -v 600  /var/log/btmp

        ;;

    607)
        echo "6.7. Linux-4.15.3 API Headers"
        # https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.15.3.tar.xz

        provide linux-4.15.3 linux-4.15.3.tar.xz

        make mrproper

        make INSTALL_HDR_PATH=dest headers_install
        find dest/include \( -name .install -o -name ..install.cmd \) -delete
        cp -rv dest/include/* /usr/include

        ;;

    608)
        echo "6.8. Man-pages-4.15"
        # https://www.kernel.org/pub/linux/docs/man-pages/man-pages-4.15.tar.xz

        provide man-pages-4.15 man-pages-4.15.tar.xz

        make install

        ;;

    609)
        echo "6.9. Glibc-2.27"
        # http://ftp.gnu.org/gnu/glibc/glibc-2.27.tar.xz
        # http://www.linuxfromscratch.org/patches/lfs/8.2/glibc-2.27-fhs-1.patch

        provide glibc-2.27 glibc-2.27.tar.xz

        patch -Np1 -i ../glibc-2.27-fhs-1.patch

        ln -sfv /tools/lib/gcc /usr/lib

        case $(uname -m) in
            i?86)   GCC_INCDIR=/usr/lib/gcc/$(uname -m)-pc-linux-gnu/7.3.0/include
                    ln -sfv ld-linux.so.2 /lib/ld-lsb.so.3
                    ;;
            x86_64) GCC_INCDIR=/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include
                    ln -sfv ../lib/ld-linux-x86-64.so.2 /lib64
                    ln -sfv ../lib/ld-linux-x86-64.so.2 /lib64/ld-lsb-x86-64.so.3
            ;;
        esac

        rm -f /usr/include/limits.h

        mkdir -v build
        cd       build

        CC="gcc -isystem $GCC_INCDIR -isystem /usr/include" \
        ../configure --prefix=/usr                          \
                     --disable-werror                       \
                     --enable-kernel=3.2                    \
                     --enable-stack-protector=strong        \
                     libc_cv_slibdir=/lib
        unset GCC_INCDIR

        make

        make check

        touch /etc/ld.so.conf

        sed '/test-installation/s@$(PERL)@echo not running@' -i ../Makefile

        make install

        cp -v ../nscd/nscd.conf /etc/nscd.conf
        mkdir -pv /var/cache/nscd

        mkdir -pv /usr/lib/locale
        localedef -i cs_CZ -f UTF-8 cs_CZ.UTF-8
        localedef -i de_DE -f ISO-8859-1 de_DE
        localedef -i de_DE@euro -f ISO-8859-15 de_DE@euro
        localedef -i de_DE -f UTF-8 de_DE.UTF-8
        localedef -i en_GB -f UTF-8 en_GB.UTF-8
        localedef -i en_HK -f ISO-8859-1 en_HK
        localedef -i en_PH -f ISO-8859-1 en_PH
        localedef -i en_US -f ISO-8859-1 en_US
        localedef -i en_US -f UTF-8 en_US.UTF-8
        localedef -i es_MX -f ISO-8859-1 es_MX
        localedef -i fa_IR -f UTF-8 fa_IR
        localedef -i fr_FR -f ISO-8859-1 fr_FR
        localedef -i fr_FR@euro -f ISO-8859-15 fr_FR@euro
        localedef -i fr_FR -f UTF-8 fr_FR.UTF-8
        localedef -i it_IT -f ISO-8859-1 it_IT
        localedef -i it_IT -f UTF-8 it_IT.UTF-8
        localedef -i ja_JP -f EUC-JP ja_JP
        localedef -i ru_RU -f KOI8-R ru_RU.KOI8-R
        localedef -i ru_RU -f UTF-8 ru_RU.UTF-8
        localedef -i tr_TR -f UTF-8 tr_TR.UTF-8
        localedef -i zh_CN -f GB18030 zh_CN.GB18030



esac