#!/bin/bash

Title='5.4. Binutils-2.30 - Pass 1'
Name=binutils-1
Version=2.30
Supplies=(http://ftp.gnu.org/gnu/binutils/binutils-2.30.tar.xz)
BuildIn=build

Build()
{
    ../configure \
        --prefix=/tools             \
        --with-sysroot=$LFS         \
        --with-lib-path=/tools/lib  \
        --target=$LFS_TGT           \
        --disable-nls               \
        --disable-werror

    make
    mkdir -v /tools/lib && ln -sv lib /tools/lib64     

    make install
}
