#!/bin/bash

Title="5.10. GCC-7.3.0 - Pass 2"
Name=gcc-2
Version=7.3.0
Supplies=(
    http://ftp.gnu.org/gnu/gcc/gcc-7.3.0/gcc-7.3.0.tar.xz
    http://www.mpfr.org/mpfr-4.0.1/mpfr-4.0.1.tar.xz
    http://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.xz
    https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz
)
BuildIn=build

Prepare() {

    ln --verbose --symbolic ../mpfr-4.0.1 mpfr
    ln --verbose --symbolic ../gmp-6.1.2 gmp
    ln --verbose --symbolic ../mpc-1.1.0 mpc
 
    cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
        `dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/include-fixed/limits.h

    for file in gcc/config/{linux,i386/linux{,64}}.h
    do
        cp -uv $file{,.orig}
        sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \
            -e 's@/usr@/tools@g' $file.orig > $file
        echo '
#undef STANDARD_STARTFILE_PREFIX_1
#undef STANDARD_STARTFILE_PREFIX_2
#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"
#define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
        touch $file.orig
    done

    sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64
}

Build()
{
    CC=$LFS_TGT-gcc                                     \
    CXX=$LFS_TGT-g++                                    \
    AR=$LFS_TGT-ar                                      \
    RANLIB=$LFS_TGT-ranlib                              \
    ../configure                                        \
        --prefix=/tools                                 \
        --with-local-prefix=/tools                      \
        --with-native-system-header-dir=/tools/include  \
        --enable-languages=c,c++                        \
        --disable-libstdcxx-pch                         \
        --disable-multilib                              \
        --disable-bootstrap                             \
        --disable-libgomp

    make

    make install
    ln -sv gcc /tools/bin/cc
}
