#!/bin/bash

Title="5.16. Bash-4.4.18"
Name=bash
Version=4.4.18
Supplies=(http://ftp.gnu.org/gnu/bash/bash-4.4.18.tar.gz)

Build()
{
    ./configure --prefix=/tools --without-bash-malloc

    make
    
    make install
    ln -sv bash /tools/bin/sh
}
