#!/bin/bash

Title="5.19. Coreutils-8.29"
Name=coreutils
Version=8.29
Supplies=(http://ftp.gnu.org/gnu/coreutils/coreutils-8.29.tar.xz)

Build() 
{
    ./configure --prefix=/tools --enable-install-program=hostname
    make
    make install
}
