#!/bin/bash

Title="5.20. Diffutils-3.6"
Name=diffutils
Version=3.6
Supplies=(http://ftp.gnu.org/gnu/diffutils/diffutils-3.6.tar.xz)

Build() 
{
    ./configure --prefix=/tools
    make
    make install
}
